/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Leonel
 */
public class information extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    public information() {
        initComponents();
        jPPerfil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpbakground = new javax.swing.JPanel();
        jpmenu = new javax.swing.JPanel();
        lbTituloMenu = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnClasificación = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jpHome = new javax.swing.JPanel();
        btnTituloHome = new javax.swing.JLabel();
        jPPerfil = new javax.swing.JPanel();
        btnTituloPerfil = new javax.swing.JLabel();
        jPClasificacion = new javax.swing.JPanel();
        btnTituloHome1 = new javax.swing.JLabel();
        jPBuscar = new javax.swing.JPanel();
        btnTituloHome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpbakground.setBackground(new java.awt.Color(255, 255, 255));

        jpmenu.setBackground(new java.awt.Color(49, 57, 69));

        lbTituloMenu.setBackground(new java.awt.Color(255, 255, 255));
        lbTituloMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lbTituloMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloMenu.setText("Usuarios");
        lbTituloMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setBackground(new java.awt.Color(49, 57, 69));
        btnHome.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Inicio");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnClasificación.setBackground(new java.awt.Color(49, 57, 69));
        btnClasificación.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnClasificación.setForeground(new java.awt.Color(255, 255, 255));
        btnClasificación.setText("Clasificación");
        btnClasificación.setBorder(null);
        btnClasificación.setBorderPainted(false);
        btnClasificación.setContentAreaFilled(false);
        btnClasificación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificaciónActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(49, 57, 69));
        btnPerfil.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.setBorderPainted(false);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(49, 57, 69));
        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpmenuLayout = new javax.swing.GroupLayout(jpmenu);
        jpmenu.setLayout(jpmenuLayout);
        jpmenuLayout.setHorizontalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenuLayout.createSequentialGroup()
                .addGroup(jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpmenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpmenuLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClasificación, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpmenuLayout.setVerticalGroup(
            jpmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloMenu)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClasificación, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpHome.setBackground(new java.awt.Color(233, 235, 237));

        btnTituloHome.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        btnTituloHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTituloHome.setText("Ofertas de trabajo");
        btnTituloHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTituloHome, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTituloHome)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jPPerfil.setBackground(new java.awt.Color(233, 235, 237));

        btnTituloPerfil.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        btnTituloPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTituloPerfil.setText("Perfil");
        btnTituloPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPPerfilLayout = new javax.swing.GroupLayout(jPPerfil);
        jPPerfil.setLayout(jPPerfilLayout);
        jPPerfilLayout.setHorizontalGroup(
            jPPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTituloPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        jPPerfilLayout.setVerticalGroup(
            jPPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPerfilLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTituloPerfil)
                .addGap(0, 387, Short.MAX_VALUE))
        );

        jPClasificacion.setBackground(new java.awt.Color(233, 235, 237));

        btnTituloHome1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        btnTituloHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTituloHome1.setText("Clasificación");
        btnTituloHome1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPClasificacionLayout = new javax.swing.GroupLayout(jPClasificacion);
        jPClasificacion.setLayout(jPClasificacionLayout);
        jPClasificacionLayout.setHorizontalGroup(
            jPClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTituloHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        jPClasificacionLayout.setVerticalGroup(
            jPClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClasificacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTituloHome1)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        btnTituloHome2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        btnTituloHome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTituloHome2.setText("Ofertas");
        btnTituloHome2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPBuscarLayout = new javax.swing.GroupLayout(jPBuscar);
        jPBuscar.setLayout(jPBuscarLayout);
        jPBuscarLayout.setHorizontalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTituloHome2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        jPBuscarLayout.setVerticalGroup(
            jPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTituloHome2)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpbakgroundLayout = new javax.swing.GroupLayout(jpbakground);
        jpbakground.setLayout(jpbakgroundLayout);
        jpbakgroundLayout.setHorizontalGroup(
            jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpbakgroundLayout.createSequentialGroup()
                .addComponent(jpmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbakgroundLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jPPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbakgroundLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(jPClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpbakgroundLayout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(jPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpbakgroundLayout.setVerticalGroup(
            jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPClasificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpbakgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpbakground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpbakground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        jPPerfil.setVisible(true);
        jPClasificacion.setVisible(false);
        jPBuscar.setVisible(false);
        jpHome.setVisible(false);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        jPPerfil.setVisible(false);
        jPClasificacion.setVisible(false);
        jPBuscar.setVisible(false);
        jpHome.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnClasificaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificaciónActionPerformed
        jPPerfil.setVisible(true);
        jPClasificacion.setVisible(true);
        jPBuscar.setVisible(false);
        jpHome.setVisible(false);
    }//GEN-LAST:event_btnClasificaciónActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        jPPerfil.setVisible(true);
        jPClasificacion.setVisible(false);
        jPBuscar.setVisible(true);
        jpHome.setVisible(false);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnClasificación;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel btnTituloHome;
    private javax.swing.JLabel btnTituloHome1;
    private javax.swing.JLabel btnTituloHome2;
    private javax.swing.JLabel btnTituloPerfil;
    private javax.swing.JPanel jPBuscar;
    private javax.swing.JPanel jPClasificacion;
    private javax.swing.JPanel jPPerfil;
    private javax.swing.JPanel jpHome;
    private javax.swing.JPanel jpbakground;
    private javax.swing.JPanel jpmenu;
    private javax.swing.JLabel lbTituloMenu;
    // End of variables declaration//GEN-END:variables
}
